Case for quantum Notebook translated
Huthayfa0/qiskit_textbook_bzu_qc pull request #11
Opened 2024-10-14 14:59 UTC by nooretk

I've translated the notebook

2024-10-24 06:58 UTC, AM3334 requested changes
here's a file of suggested changes 
[Nour's case.docx](https://github.com/user-attachments/files/17502572/Nour.s.case.docx)

2024-10-31 22:45 UTC, AM3334 commented
@nooretk ,what happened with you?

2024-11-03 09:16 UTC, nooretk commented
@AM3334 I made the changes and saved the file

2024-11-03 10:18 UTC, AM3334 approved these changes

2024-11-03 10:18 UTC, merged